name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    - aicrowd-api
    - aicrowd-gym
    - gym3
    - attrs
    - tensorboard
    - pytorch-lightning==1.6.1
    - einops
    - setuptools==59.5.0
    - moviepy
